#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     IRSensor3,      sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     IRSensor4,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     liftLbottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     liftRbottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     LED,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     leadL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     leadR,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoL,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoR,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    lockL,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    lockR,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    auton,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//WAFFLEBOT TELEOP

#include "JoystickDriver.c"

task main(){
	waitForStart();
  getJoystickSettings(joystick);
  int joy1y1, joy1y2, joy2y1, joy2y2;
  while(true){
  	joy1y1 = joystick.joy1_y1;
 		joy1y2 = joystick.joy1_y2;
 		joy2y1 = joystick.joy2_y1;
 		joy2y2 = joystick.joy2_y2;
 		if ((joy1Btn(1)) || (joy2Btn(1)))
			servo[auton] = 175;
 		if ((joy1Btn(2)) || (joy2Btn(2)))
			servo[auton] = 0;
		if ((joy1Btn(4)) || (joy2Btn(4)))
			servo[auton] = 255;
		if (abs(joy1y1) >= 15)
			motor[right] = (joy1y1+72)/2;
		else
			motor[right] = 0;
		if (abs(joy1y2) >= 15)
			motor[left] = (joy1y2+72)/2;
		else
			motor[left] = 0;
		if (abs(joy2y1) >= 50)
			motor[leadL] = (joy2y1+72)/2;
		else
			motor[leadL] = 0;
		if (abs(joy2y2) > 50)
			motor[leadR] = (joy2y2+72)/2;
		else
			motor[leadR] = 0;
		if ((joy1Btn(6)) || (joy2Btn(6))){ //up
			motor[liftRbottom] = 100;
			motor[liftLbottom] = -100;
		}
		else if ((joy1Btn(8)) || (joy2Btn(8))){ //down
			motor[liftRbottom] = -100;
			motor[liftLbottom] = 100;
		}
		else {
			motor[liftRbottom] = 0;
			motor[liftLbottom] = 0;
		}
		//LOCK ARMSHHH
		if ((joy1Btn(3)) || (joy2Btn(3))){
			servo[auton] = 175;
			servo[lockL] = 255;
			servo[lockR] = 0;
		}
		else {
			servo[lockL] = 100;
			servo[lockR] = 155;
		}
		if ((joy1Btn(5)) || (joy2Btn(5))){
			servo[servoR] = 255;
			servo[servoL] = 0;
		}
		if ((joy1Btn(7)) || (joy2Btn(7))){
			servo[servoR] = 0;
			servo[servoL] = 255;
		}
		if ((joy1Btn(9)) || (joy2Btn(9)))
			motor[LED] = 100;
		else if ((joy1Btn(10)) || (joy2Btn(10)))
			motor[LED] = 0;
	}
}
